[package]
name = "read-partitions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mbrman = "0.4.2"
clap = { version ="3.0", features = ["derive"]}